// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "10.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Domain.ApiKeys.ApiKey", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("KeyHash")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("key_hash");

            b.Property<string>("KeyId")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("key_id");

            b.Property<string>("Label")
                .HasColumnType("text")
                .HasColumnName("label");

            b.Property<DateTime?>("LastUsedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("last_used_at");

            b.Property<string>("Prefix")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("prefix");

            b.Property<DateTime?>("RevokedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("revoked_at");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("Id")
                .HasName("pk_api_keys");

            b.HasIndex("KeyId")
                .IsUnique()
                .HasDatabaseName("ix_api_keys_key_id");

            b.HasIndex("UserId")
                .HasDatabaseName("ix_api_keys_user_id");

            b.ToTable("api_keys", "public");
        });

        modelBuilder.Entity("Domain.Files.File", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("ContentType")
                .HasColumnType("text")
                .HasColumnName("content_type");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("RelativePath")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("relative_path");

            b.Property<string>("Sha256")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("sha256");

            b.Property<Guid>("ShareId")
                .HasColumnType("uuid")
                .HasColumnName("share_id");

            b.Property<int>("Size")
                .HasColumnType("integer")
                .HasColumnName("size");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_files");

            b.HasIndex("ShareId")
                .HasDatabaseName("ix_files_share_id");

            b.ToTable("files", "public");
        });

        modelBuilder.Entity("Domain.Shares.Share", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<int>("ConfiguredTtlMinutes")
                .HasColumnType("integer")
                .HasColumnName("configured_ttl_minutes");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<DateTime>("ExpiresAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("expires_at");

            b.Property<int>("FileCount")
                .HasColumnType("integer")
                .HasColumnName("file_count");

            b.Property<Guid>("OwnerUserId")
                .HasColumnType("uuid")
                .HasColumnName("owner_user_id");

            b.Property<string>("Status")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("status");

            b.Property<long>("TotalBytes")
                .HasColumnType("bigint")
                .HasColumnName("total_bytes");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_shares");

            b.HasIndex("ExpiresAt")
                .HasDatabaseName("ix_shares_expires_at");

            b.HasIndex("OwnerUserId")
                .HasDatabaseName("ix_shares_owner_user_id");

            b.ToTable("shares", "public");
        });

        modelBuilder.Entity("Domain.Users.User", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("Email")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("email");

            b.Property<string>("Name")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("name");

            b.HasKey("Id")
                .HasName("pk_users");

            b.ToTable("users", "public");
        });

        modelBuilder.Entity("Domain.ApiKeys.ApiKey", b =>
        {
            b.HasOne("Domain.Users.User", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_api_keys_users_user_id");
        });

        modelBuilder.Entity("Domain.Files.File", b =>
        {
            b.HasOne("Domain.Shares.Share", null)
                .WithMany()
                .HasForeignKey("ShareId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_files_shares_share_id");
        });

        modelBuilder.Entity("Domain.Shares.Share", b =>
        {
            b.HasOne("Domain.Users.User", null)
                .WithMany()
                .HasForeignKey("OwnerUserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                .HasConstraintName("fk_shares_users_owner_user_id");
        });
#pragma warning restore 612, 618
    }
}
