services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      - POSTGRES_DB=share
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80

volumes:
  postgres_data: