services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      - POSTGRES_DB=share
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    volumes:
      - seq_data:/data
    ports:
      - 8081:80
      - 5341:5341

volumes:
  postgres_data:
  seq_data:
