<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Share.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\domain\Share.Domain.csproj" />
    <ProjectReference Include="..\..\shared-libs\shared-kernal\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Share.Application.UnitTests" />
  </ItemGroup>

</Project>
