#!/usr/bin/env bash
#
# Collects the three build outputs into a self-contained Docker build context.
#
# This script never builds anything. Nx produces the inputs through the `dependsOn` entries on the
# app-image `build` target (web:build, api:publish, app-image:build-host), so each one is cached and
# rebuilt on its own terms.
#
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$repo_root"

project_dir="apps/app-image"
staging_dir="dist/apps/app-image"
context_dir="${staging_dir}/context"

web_dist="dist/apps/web"
host_publish="${staging_dir}/host"

fail() { printf 'stage-artifacts: %s\n' "$*" >&2; exit 1; }

# The API is published by the Nx dotnet plugin's inferred `publish` target, which writes to
# bin/<configuration>/<tfm>/publish. The target framework is discovered rather than hardcoded so a
# TFM bump does not silently break the image build.
find_api_publish() {
  local matches=()
  while IFS= read -r -d '' candidate; do
    matches+=("$candidate")
  done < <(find apps/api/bin/Release -mindepth 2 -maxdepth 2 -type d -name publish -print0 2>/dev/null)

  (( ${#matches[@]} > 0 )) || fail "no API publish output under apps/api/bin/Release. Run: nx run api:publish"
  (( ${#matches[@]} == 1 )) || fail "found ${#matches[@]} API publish directories; clean apps/api/bin and rebuild."

  printf '%s' "${matches[0]}"
}

# Reads the entry assembly name from the published <name>.runtimeconfig.json, so nothing downstream
# has to hardcode "Api.dll" or "AppImage.Host.dll".
entry_assembly() {
  local dir="$1" runtimeconfig name
  runtimeconfig="$(find "$dir" -maxdepth 1 -name '*.runtimeconfig.json' -print -quit)"
  [[ -n "$runtimeconfig" ]] || fail "no *.runtimeconfig.json in ${dir}; that directory is not a published .NET application."

  name="$(basename "$runtimeconfig" .runtimeconfig.json)"
  [[ -f "${dir}/${name}.dll" ]] || fail "${dir}/${name}.dll is missing."

  printf '%s' "${name}.dll"
}

# The apphost is a native executable for whatever platform published it — on a developer's Mac that
# is a Mach-O binary that would be dead weight in a Linux image. The container starts the app with
# `dotnet <name>.dll`, so it is never used.
drop_apphost() {
  # Assigned separately: bash 3.2, which is what macOS ships, does not make `dir` visible to a later
  # assignment in the same `local` statement.
  local dir="$1"
  local apphost="${dir}/${2%.dll}"
  rm -f "$apphost" "${apphost}.exe"
}

[[ -d "$web_dist" ]] || fail "no web build output at ${web_dist}. Run: nx build web"
[[ -f "${web_dist}/index.html" ]] || fail "${web_dist}/index.html is missing; that is not a web production build."
[[ -d "$host_publish" ]] || fail "no host publish output at ${host_publish}. Run: nx run app-image:build-host"

api_publish="$(find_api_publish)"

rm -rf "$context_dir"
mkdir -p "${context_dir}/api" "${context_dir}/host" "${context_dir}/web"

cp -R "${api_publish}/." "${context_dir}/api"
cp -R "${host_publish}/." "${context_dir}/host"
cp -R "${web_dist}/." "${context_dir}/web"
cp "${project_dir}/Dockerfile" "${context_dir}/Dockerfile"
cp "${project_dir}/docker-entrypoint.sh" "${context_dir}/docker-entrypoint.sh"
chmod 0755 "${context_dir}/docker-entrypoint.sh"

api_dll="$(entry_assembly "${context_dir}/api")"
host_dll="$(entry_assembly "${context_dir}/host")"
drop_apphost "${context_dir}/api" "$api_dll"
drop_apphost "${context_dir}/host" "$host_dll"

# package.json is Nx/Vite build metadata, not something the browser ever asks for.
rm -f "${context_dir}/web/package.json"

# Sourced by docker-entrypoint.sh. The one place assembly names cross from the build into the image.
cat > "${context_dir}/app.env" <<EOF
# Generated by apps/app-image/tools/stage-artifacts.sh. Do not edit.
APP_IMAGE_API_DLL=${api_dll}
APP_IMAGE_HOST_DLL=${host_dll}
EOF

printf 'stage-artifacts: context ready at %s (api=%s, host=%s)\n' "$context_dir" "$api_dll" "$host_dll"
